/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EngagementModelRouteImport } from './routes/engagement-model'
import { Route as GccRouteImport } from './routes/gcc'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SettingUpInIndiaRouteImport } from './routes/setting-up-in-india'
import { Route as WhoWeServeRouteImport } from './routes/who-we-serve'
import { Route as ServicesGrowRouteImport } from './routes/services.grow'
import { Route as ServicesManageRouteImport } from './routes/services.manage'
import { Route as ServicesSetupRouteImport } from './routes/services.setup'
import { Route as WhoWeServeEnteringIndiaRouteImport } from './routes/who-we-serve.entering-india'
import { Route as WhoWeServeFundedStartupsRouteImport } from './routes/who-we-serve.funded-startups'
import { Route as WhoWeServeMidMarketRouteImport } from './routes/who-we-serve.mid-market'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EngagementModelRoute = EngagementModelRouteImport.update({
  id: '/engagement-model',
  path: '/engagement-model',
  getParentRoute: () => rootRouteImport,
} as any)
const GccRoute = GccRouteImport.update({
  id: '/gcc',
  path: '/gcc',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingUpInIndiaRoute = SettingUpInIndiaRouteImport.update({
  id: '/setting-up-in-india',
  path: '/setting-up-in-india',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoWeServeRoute = WhoWeServeRouteImport.update({
  id: '/who-we-serve',
  path: '/who-we-serve',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesGrowRoute = ServicesGrowRouteImport.update({
  id: '/grow',
  path: '/grow',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesManageRoute = ServicesManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSetupRoute = ServicesSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => ServicesRoute,
} as any)
const WhoWeServeEnteringIndiaRoute = WhoWeServeEnteringIndiaRouteImport.update({
  id: '/entering-india',
  path: '/entering-india',
  getParentRoute: () => WhoWeServeRoute,
} as any)
const WhoWeServeFundedStartupsRoute =
  WhoWeServeFundedStartupsRouteImport.update({
    id: '/funded-startups',
    path: '/funded-startups',
    getParentRoute: () => WhoWeServeRoute,
  } as any)
const WhoWeServeMidMarketRoute = WhoWeServeMidMarketRouteImport.update({
  id: '/mid-market',
  path: '/mid-market',
  getParentRoute: () => WhoWeServeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/engagement-model': typeof EngagementModelRoute
  '/gcc': typeof GccRoute
  '/insights': typeof InsightsRoute
  '/services': typeof ServicesRouteWithChildren
  '/setting-up-in-india': typeof SettingUpInIndiaRoute
  '/who-we-serve': typeof WhoWeServeRouteWithChildren
  '/services/grow': typeof ServicesGrowRoute
  '/services/manage': typeof ServicesManageRoute
  '/services/setup': typeof ServicesSetupRoute
  '/who-we-serve/entering-india': typeof WhoWeServeEnteringIndiaRoute
  '/who-we-serve/funded-startups': typeof WhoWeServeFundedStartupsRoute
  '/who-we-serve/mid-market': typeof WhoWeServeMidMarketRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/engagement-model': typeof EngagementModelRoute
  '/gcc': typeof GccRoute
  '/insights': typeof InsightsRoute
  '/services': typeof ServicesRouteWithChildren
  '/setting-up-in-india': typeof SettingUpInIndiaRoute
  '/who-we-serve': typeof WhoWeServeRouteWithChildren
  '/services/grow': typeof ServicesGrowRoute
  '/services/manage': typeof ServicesManageRoute
  '/services/setup': typeof ServicesSetupRoute
  '/who-we-serve/entering-india': typeof WhoWeServeEnteringIndiaRoute
  '/who-we-serve/funded-startups': typeof WhoWeServeFundedStartupsRoute
  '/who-we-serve/mid-market': typeof WhoWeServeMidMarketRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/engagement-model': typeof EngagementModelRoute
  '/gcc': typeof GccRoute
  '/insights': typeof InsightsRoute
  '/services': typeof ServicesRouteWithChildren
  '/setting-up-in-india': typeof SettingUpInIndiaRoute
  '/who-we-serve': typeof WhoWeServeRouteWithChildren
  '/services/grow': typeof ServicesGrowRoute
  '/services/manage': typeof ServicesManageRoute
  '/services/setup': typeof ServicesSetupRoute
  '/who-we-serve/entering-india': typeof WhoWeServeEnteringIndiaRoute
  '/who-we-serve/funded-startups': typeof WhoWeServeFundedStartupsRoute
  '/who-we-serve/mid-market': typeof WhoWeServeMidMarketRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/engagement-model'
    | '/gcc'
    | '/insights'
    | '/services'
    | '/setting-up-in-india'
    | '/who-we-serve'
    | '/services/grow'
    | '/services/manage'
    | '/services/setup'
    | '/who-we-serve/entering-india'
    | '/who-we-serve/funded-startups'
    | '/who-we-serve/mid-market'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/engagement-model'
    | '/gcc'
    | '/insights'
    | '/services'
    | '/setting-up-in-india'
    | '/who-we-serve'
    | '/services/grow'
    | '/services/manage'
    | '/services/setup'
    | '/who-we-serve/entering-india'
    | '/who-we-serve/funded-startups'
    | '/who-we-serve/mid-market'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/case-studies'
    | '/contact'
    | '/engagement-model'
    | '/gcc'
    | '/insights'
    | '/services'
    | '/setting-up-in-india'
    | '/who-we-serve'
    | '/services/grow'
    | '/services/manage'
    | '/services/setup'
    | '/who-we-serve/entering-india'
    | '/who-we-serve/funded-startups'
    | '/who-we-serve/mid-market'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  EngagementModelRoute: typeof EngagementModelRoute
  GccRoute: typeof GccRoute
  InsightsRoute: typeof InsightsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SettingUpInIndiaRoute: typeof SettingUpInIndiaRoute
  WhoWeServeRoute: typeof WhoWeServeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engagement-model': {
      id: '/engagement-model'
      path: '/engagement-model'
      fullPath: '/engagement-model'
      preLoaderRoute: typeof EngagementModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gcc': {
      id: '/gcc'
      path: '/gcc'
      fullPath: '/gcc'
      preLoaderRoute: typeof GccRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setting-up-in-india': {
      id: '/setting-up-in-india'
      path: '/setting-up-in-india'
      fullPath: '/setting-up-in-india'
      preLoaderRoute: typeof SettingUpInIndiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who-we-serve': {
      id: '/who-we-serve'
      path: '/who-we-serve'
      fullPath: '/who-we-serve'
      preLoaderRoute: typeof WhoWeServeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/grow': {
      id: '/services/grow'
      path: '/grow'
      fullPath: '/services/grow'
      preLoaderRoute: typeof ServicesGrowRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/manage': {
      id: '/services/manage'
      path: '/manage'
      fullPath: '/services/manage'
      preLoaderRoute: typeof ServicesManageRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/setup': {
      id: '/services/setup'
      path: '/setup'
      fullPath: '/services/setup'
      preLoaderRoute: typeof ServicesSetupRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/who-we-serve/entering-india': {
      id: '/who-we-serve/entering-india'
      path: '/entering-india'
      fullPath: '/who-we-serve/entering-india'
      preLoaderRoute: typeof WhoWeServeEnteringIndiaRouteImport
      parentRoute: typeof WhoWeServeRoute
    }
    '/who-we-serve/funded-startups': {
      id: '/who-we-serve/funded-startups'
      path: '/funded-startups'
      fullPath: '/who-we-serve/funded-startups'
      preLoaderRoute: typeof WhoWeServeFundedStartupsRouteImport
      parentRoute: typeof WhoWeServeRoute
    }
    '/who-we-serve/mid-market': {
      id: '/who-we-serve/mid-market'
      path: '/mid-market'
      fullPath: '/who-we-serve/mid-market'
      preLoaderRoute: typeof WhoWeServeMidMarketRouteImport
      parentRoute: typeof WhoWeServeRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesGrowRoute: typeof ServicesGrowRoute
  ServicesManageRoute: typeof ServicesManageRoute
  ServicesSetupRoute: typeof ServicesSetupRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesGrowRoute: ServicesGrowRoute,
  ServicesManageRoute: ServicesManageRoute,
  ServicesSetupRoute: ServicesSetupRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

interface WhoWeServeRouteChildren {
  WhoWeServeEnteringIndiaRoute: typeof WhoWeServeEnteringIndiaRoute
  WhoWeServeFundedStartupsRoute: typeof WhoWeServeFundedStartupsRoute
  WhoWeServeMidMarketRoute: typeof WhoWeServeMidMarketRoute
}

const WhoWeServeRouteChildren: WhoWeServeRouteChildren = {
  WhoWeServeEnteringIndiaRoute: WhoWeServeEnteringIndiaRoute,
  WhoWeServeFundedStartupsRoute: WhoWeServeFundedStartupsRoute,
  WhoWeServeMidMarketRoute: WhoWeServeMidMarketRoute,
}

const WhoWeServeRouteWithChildren = WhoWeServeRoute._addFileChildren(
  WhoWeServeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  EngagementModelRoute: EngagementModelRoute,
  GccRoute: GccRoute,
  InsightsRoute: InsightsRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SettingUpInIndiaRoute: SettingUpInIndiaRoute,
  WhoWeServeRoute: WhoWeServeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
